development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://dkqkkztqarulac:HJEOIPn2BHbMqTLaXVgvm0YPOs@ec2-50-19-117-114.compute-1.amazonaws.com:5432/d4li9h41stto6u
